/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.lifray.amf.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the UserExtra service. Represents a row in the &quot;AMF_UserExtra&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.lifray.amf.model.impl.UserExtraModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.lifray.amf.model.impl.UserExtraImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see UserExtra
 * @generated
 */
@ProviderType
public interface UserExtraModel extends BaseModel<UserExtra> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a user extra model instance should use the {@link UserExtra} interface instead.
	 */

	/**
	 * Returns the primary key of this user extra.
	 *
	 * @return the primary key of this user extra
	 */
	public String getPrimaryKey();

	/**
	 * Sets the primary key of this user extra.
	 *
	 * @param primaryKey the primary key of this user extra
	 */
	public void setPrimaryKey(String primaryKey);

	/**
	 * Returns the uuid of this user extra.
	 *
	 * @return the uuid of this user extra
	 */
	@AutoEscape
	public String getUuid();

	/**
	 * Sets the uuid of this user extra.
	 *
	 * @param uuid the uuid of this user extra
	 */
	public void setUuid(String uuid);

	/**
	 * Returns the username of this user extra.
	 *
	 * @return the username of this user extra
	 */
	@AutoEscape
	public String getUsername();

	/**
	 * Sets the username of this user extra.
	 *
	 * @param username the username of this user extra
	 */
	public void setUsername(String username);

	/**
	 * Returns the user ID of this user extra.
	 *
	 * @return the user ID of this user extra
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this user extra.
	 *
	 * @param userId the user ID of this user extra
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this user extra.
	 *
	 * @return the user uuid of this user extra
	 */
	public String getUserUuid();

	/**
	 * Sets the user uuid of this user extra.
	 *
	 * @param userUuid the user uuid of this user extra
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the mobile phone of this user extra.
	 *
	 * @return the mobile phone of this user extra
	 */
	public long getMobilePhone();

	/**
	 * Sets the mobile phone of this user extra.
	 *
	 * @param mobilePhone the mobile phone of this user extra
	 */
	public void setMobilePhone(long mobilePhone);

	/**
	 * Returns the home phone of this user extra.
	 *
	 * @return the home phone of this user extra
	 */
	public long getHomePhone();

	/**
	 * Sets the home phone of this user extra.
	 *
	 * @param homePhone the home phone of this user extra
	 */
	public void setHomePhone(long homePhone);

	/**
	 * Returns the security question of this user extra.
	 *
	 * @return the security question of this user extra
	 */
	@AutoEscape
	public String getSecurityQuestion();

	/**
	 * Sets the security question of this user extra.
	 *
	 * @param securityQuestion the security question of this user extra
	 */
	public void setSecurityQuestion(String securityQuestion);

	/**
	 * Returns the security question answer of this user extra.
	 *
	 * @return the security question answer of this user extra
	 */
	@AutoEscape
	public String getSecurityQuestionAnswer();

	/**
	 * Sets the security question answer of this user extra.
	 *
	 * @param securityQuestionAnswer the security question answer of this user extra
	 */
	public void setSecurityQuestionAnswer(String securityQuestionAnswer);

}